const mongoose = require('mongoose');

// Id field automatically generated by mongoose.
const thingSchema = mongoose.Schema({
  title: { type: String, required: true },
  description: { type: String, required: true },
  userId: { type: String, required: true }
});

module.exports = mongoose.model('Thing', thingSchema);
